[package]
authors = ["Inflation <hypernovagama@gmail.com>"]
description = "Safe Rust wrapper for JPEG XL reference implementation"
edition = "2018"
exclude = ["test/"]
license = "GPL-3.0-or-later"
name = "jpegxl-rs"
readme = "README.md"
repository = "https://github.com/inflation/jpegxl-rs"
version = "0.2.4-alpha.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["image"]
docsrs = ["jpegxl-sys/docsrs"]
with-rayon = ["rayon"]
without-build = ["jpegxl-sys/without-build"]
without-image = []
without-threads = ["jpegxl-sys/without-threads"]

[dependencies]
image = {version = "0.23.12", optional = true}
jpegxl-sys = "0.2.3"
rayon = {version = "1.5.0", optional = true}
thiserror = "1.0.23"

[dev-dependencies]
criterion = "0.3"
image = "0.23.12"

[package.metadata.docs.rs]
features = ["docsrs", "with-rayon"]

[lib]
bench = false

[[bench]]
harness = false
name = "decode"
