[package]
authors = ["Inflation <hypernovagama@gmail.com>"]
description = "Safe Rust wrapper for JPEG XL reference implementation"
edition = "2018"
exclude = ["test/"]
license = "GPL-3.0-or-later"
name = "jpegxl-rs"
readme = "README.md"
repository = "https://github.com/inflation/jpegxl-rs"
version = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["jpegxl-sys/default"]
docsrs = ["jpegxl-sys/docsrs"]
with-image = ["image"]

[dependencies]
image = {version = "0.23.8", optional = true}
jpegxl-sys = {version = "0.1.4", default-features = false, optional = true}

[dev-dependencies]
image = "0.23.8"

[package.metadata.docs.rs]
features = ["docsrs", "with-image"]
no-default-features = true
