[package]
authors = ["Inflation <hypernovagama@gmail.com>"]
categories = ["api-bindings", "encoding", "multimedia::images"]
description = "Safe Rust wrapper for JPEG XL reference implementation"
edition = "2021"
keywords = ["jpeg-xl", "jxl"]
license = "GPL-3.0-or-later"
name = "jpegxl-rs"
readme = "README.md"
repository = "https://github.com/inflation/jpegxl-rs"
version = "0.7.1+libjxl-0.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["image", "threads"]
image = ["dep:image"]
threads = ["jpegxl-sys/threads"]
vendored = ["jpegxl-sys/vendored"]
docs = ["jpegxl-sys/docs"]

[dependencies]
derive_builder = "0.11.2"
image = { version = "0.24.4", optional = true, default-features = false }
paste = "1.0.9"
thiserror = "1.0.37"
half = "2.1.0"

[dependencies.jpegxl-sys]
version = "0.7.0"
path = "../jpegxl-sys"

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false, features = [
    "html_reports",
] }
qcms = { git = "https://github.com/FirefoxGraphics/qcms" }

[dev-dependencies.image]
version = "0.24.4"
default-features = false
features = ["jpeg", "png"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
features = ["docs"]

[lib]
bench = false
path = "src/lib.rs"

[[bench]]
harness = false
name = "decode"

[[bench]]
harness = false
name = "encode"
